import {Ionicons} from "@expo/vector-icons";

export const Icons = {
    Home: <Ionicons name="home" size={24} color="black" />,
    Settings: <Ionicons name="cog" size={24} color="black" />,
    Email: <Ionicons name="mail" size={24} color="black" />,
    Password: <Ionicons name="lock-closed" size={24} color="black" />,
    Profile: <Ionicons name="person" size={24} color="black" />,
    Logout: <Ionicons name="log-out" size={24} color="black" />,
    Login: <Ionicons name="log-in" size={24} color="black" />,
    Register: <Ionicons name="person-add" size={24} color="black" />,
    Back: <Ionicons name="arrow-back" size={24} color="black" />,
    Add: <Ionicons name="add" size={24} color="black" />,
    Search: <Ionicons name="search" size={24} color="black" />,
    Book: <Ionicons name="book" size={24} color="black" />,
    Art: <Ionicons name="color-palette" size={16} color="black" />,
    Biology: <Ionicons name="flask" size={16} color="black" />,
    Chemistry: <Ionicons name="flask" size={16} color="black" />,
    Physics: <Ionicons name="flask" size={16} color="black" />,
    Sociology: <Ionicons name="chatbubble" size={16} color="black" />,
    Civic: <Ionicons name="book" size={16} color="black" />,
    History: <Ionicons name="book" size={16} color="black" />,
    Bahasa: <Ionicons name="language" size={16} color="black" />,
    English: <Ionicons name="language" size={16} color="black" />,
    IT: <Ionicons name="code" size={16} color="black" />,
    Geography: <Ionicons name="earth" size={16} color="black" />,
    Mathematics: <Ionicons name="calculator" size={16} color="black" />,
    Sundanesse: <Ionicons name="language" size={16} color="black" />,
    Physical: <Ionicons name="walk" size={16} color="black" />,
    Religion: <Ionicons name="book" size={16} color="black" />,
    Economics: <Ionicons name="calculator" size={16} color="black" />,
    PoE: <Ionicons name="bulb" size={16} color="black" />,
};
